
default: install

install:
	@echo "Installing environment"
	@chmod +x setup/install.sh
	@./setup/install.sh

help:

	@echo "Available targets:"
	@echo "default: Install"

.PHONY: default install help